### ISSUE TITLE
Abstract for tutorial announcement

### ISSUE THREAD

**Issue by budschi** [FAIRmat-NFDI/AreaA-Documentation#5]
I drafted an abstract for the announcement of our tutorial: [abstract](https://github.com/FAIRmat-NFDI/AreaA-Documentation/blob/main/tutorial/abstract.md).
Comments and corrections are welcome, thanks.

**Comment by Pepe-Marquez** [comment]
I guess this issue can be now closed?

**Comment by budschi** [comment]
the Tutorial is now announced on the bases of this abstract
